env: "dev"
name: "coinbase"
scheme: "wss"
host: "ws-feed.exchange.coinbase.com"
path: ""
maxsize: 200
message: 
  type: "subscribe"
  product_ids: ["BTC-USD", "ETH-USD", "ETH-BTC"]
  channels: ["matches"]
